module.exports = {
  purge: ["./src/**/*.{js,jsx}", "./public/index.html"],
  darkMode: "class",
  theme: {
    extend: {
      keyframes: {
        skeletonLoadingLight: {
          "0%": { backgroundColor: "#111f0f" },
          "100%": { backgroundColor: "#008010" },
        },
        skeletonLoadingDark: {
          "0%": { backgroundColor: "#d6e8ce" },
          "100%": { backgroundColor: "#a4b39d" },
        },
      },
      animation: {
        skeletonLightBg: "skeletonLoadingLight 1s linear infinite alternate",
        skeletonDarkBg: "skeletonLoadingDark 1s linear infinite alternate",
      },
      borderRadius: { card: "93% 7% 95% 5% / 4% 92% 8% 96%" },
      colors: {
        primaryLight: "#006e0e",
        primaryLightOn: "#ffffff",
        primaryLightContainer: "#92fa89",
        primaryLightContainerOn: "#002201",
        secondaryLight: "#53634e",
        secondaryLightOn: "#ffffff",
        secondaryLightContainer: "#d6e8ce",
        secondaryLightContainerOn: "#111f0f",
        errorLight: "#ba1b1b",
        errorLightOn: "#ffffff",
        errorLightContainer: "#ffdad4",
        errorLightContainerOn: "#410001",
        backgroundLight: "#fdfdf7",
        backgroundLightOn: "#1a1c19",
        lightVariantSurface: "#dee4d8",
        lightVariantSurfaceOn: "#42493f",
        lightOutline: "#72796e",

        primaryDark: "#76dd6f",
        primaryDarkOn: "#003a03",
        primaryDarkContainer: "#005308",
        primaryDarkContainerOn: "#92fa89",
        secondaryDarkContainer: "#3c4b38",
        secondaryDarkContainerOn: "#d6e8ce",
        errorDark: "#ffb4a9",
        errorDarkOn: "#680003",
        errorDarkContainer: "#930006",
        errorDarkContainerOn: "#ffdad4",
        backgroundDark: "#1a1c19",
        backgroundDarkOn: "#e2e3dc",
        darkSurface: "#1a1c19",
        darkSurfaceOn: "#e2e3dc",
        darkVariantSurface: "#42493f",
        darkVariantSurfaceOn: "#c2c9bc",
        darkOutline: "#8c9288",
      },
    },
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "2rem",
        lg: "4rem",
        xl: "5rem",
        "2xl": "6rem",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
